#run with sudo docker-compose up --build

version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/models:/app/models:ro
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres/db"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Nginx Frontend Service
  frontend:
    image: nginx:latest
    container_name: nginx_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
